apiVersion: v1
data:
  config.toml: |
    #Possible values -- debug, info, warn, error
    log_level = "info"
    #port for the server to listen on
    port = 3030
    #CPU Threads for actix
    workers = 4
    #timeout when contacting listed services
    req_timeout = 600
    #Limit response size from your services
    max_body_size_bytes = 200000000 # 200 MB
    #For load balancer liveness Probe
    health_endpoint = "/health"
    #User agent should be <name>/<version>
    user_agent = "imgopt/0.1.8"
    #use full path if possible
    storage_path = "s3"

    #Limit which width scaling options are available (optional)
    allowed_sizes = [ 50, 100, 200, 400, 500, 600, 700, 800, 900, 1000 ]

    #Skip certain images from processing (optional)
    #skip_list = ["bafybeih6zvkw6fenaprelv45b4zjzazi3mvogvkq6ws75ywyphjk4iyqwi"]


    #Services
    [[services]]
    name = "ipfs"
    endpoint = "https://ipfs.io/ipfs"

    [[services]]
    name = "arweave"
    endpoint = "https://arweave.net"

kind: ConfigMap
metadata:
  name: imgopt-config
