os: Visual Studio 2015

cache:
  - '%USERPROFILE%\.cargo'
  - target

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-gnu

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --verbose
  - cargo run --example print_version

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
